export const nameOfCollections = {
  Conversation: 'Conversation',
  Message: 'Message',
  EndUser: 'EndUser',
  Admin: 'Admin',
  Like: 'Like',
  Post: 'Post',
  Group: 'Group',
  Event: 'Event',
  Comment: 'Comment',
  Friend: 'Friend',
  Notification: 'Notification',
  Subscription: 'subscription',
  Receipt: 'receipt',
} as const;
